name: Build Executables

on:
  push:
    branches:
      - main  # Remplace par la branche principale si nécessaire
  pull_request:

jobs:
  build:
    name: Build Binaries
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64, arm64]
        exclude:
          - os: windows-latest  # Windows ne supporte pas arm64 avec GitHub Actions
          - os: ubuntu-latest  # Ubuntu-latest sur GitHub Actions est x86_64 par défaut

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -f requirements.txt

      - name: Build binary (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          ARCH=${{ matrix.arch }}
          if [ "$ARCH" == "x86_64" ]; then
            pyinstaller --onefile --name diags-${{ runner.os }}-x86_64 --add-data "resources:resources" main.py
          else
            pyinstaller --onefile --name diags-${{ runner.os }}-arm64 --add-data "resources:resources" main.py
          fi

      - name: Build binary (Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile --name diags-windows-x86_64.exe --add-data "resources:resources "main.py

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ runner.os }}-${{ matrix.arch }}
          path: dist/*

