name: Build Python Binary

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # Peut être un problème, on en parle après

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Adapte selon ton projet

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Compile script
        run: pyinstaller --onefile HelloWorld.py

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: helloworld-binary
          path: dist/HelloWorld

